modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="ultracraft" #mandatory

version="1.0" #mandatory

displayName="Ultracraft" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="ultracraft_icon.png" #optional

credits="Thanks to self" #optional

authors="By the creator of Enhancedcraft." #optional

description='''
From the creators of Enhancedcraft, this mod does something similar.
'''

[[dependencies.ultracraft]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[32,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.ultracraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
