modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/DieselDorky16/Ultracraft/issues" #optional

[[mods]] #mandatory

modId="ultracraft" #mandatory

version="beta 1.0.0.54" #mandatory

displayName="Ultracraft" #mandatory

updateJSONURL="https://github.com/DieselDorky16/Ultracraft/releases" #optional

displayURL="https://github.com/DieselDorky16/Ultracraft" #optional

logoFile="ultracraft_icon.png" #optional

credits="Thanks to self" #optional

authors="By the creator of Enhancedcraft." #optional

description='''
From the creators of Enhancedcraft, this mod does something similar, adding new blocks and content.
'''

[[dependencies.ultracraft]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[32,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.ultracraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
